DROP TABLE aliases if exists;
   
CREATE TABLE testtable (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    column1   VARCHAR(128) NOT NULL,
    column2 VARCHAR(128) NOT NULL,
    CONSTRAINT pk_testtable PRIMARY KEY (id),
    CONSTRAINT u_aliases_col1 UNIQUE (column1),
    CONSTRAINT u_aliases_col2 UNIQUE (column2),
    CONSTRAINT u_aliases_cols UNIQUE (column1, column2)
);